/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * BigdecMany2oneP generated by hbm2java
 */
@Entity
@Table(name="`Bigdec_Many2One_P`"
)

public class BigdecMany2oneP  implements java.io.Serializable {

    
    private BigDecimal bigdecId;
    
    private BigDecimal bigDecCol1;
    
    private Set<BigdecMany2oneC> bigdecMany2oneCs = new HashSet<BigdecMany2oneC>(0);

    public BigdecMany2oneP() {
    }


    @Id 
    

    @Column(name="`BigdecID`", precision=35, scale=15)
    public BigDecimal getBigdecId() {
        return this.bigdecId;
    }
    
    public void setBigdecId(BigDecimal bigdecId) {
        this.bigdecId = bigdecId;
    }

    

    @Column(name="`BigDecCol1`", precision=35, scale=15)
    public BigDecimal getBigDecCol1() {
        return this.bigDecCol1;
    }
    
    public void setBigDecCol1(BigDecimal bigDecCol1) {
        this.bigDecCol1 = bigDecCol1;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="bigdecMany2oneP")
    public Set<BigdecMany2oneC> getBigdecMany2oneCs() {
        return this.bigdecMany2oneCs;
    }
    
    public void setBigdecMany2oneCs(Set<BigdecMany2oneC> bigdecMany2oneCs) {
        this.bigdecMany2oneCs = bigdecMany2oneCs;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof BigdecMany2oneP) )
		    return false;

		 BigdecMany2oneP that = (BigdecMany2oneP) o;

		 return ( (this.getBigdecId()==that.getBigdecId()) || ( this.getBigdecId()!=null && that.getBigdecId()!=null && this.getBigdecId().equals(that.getBigdecId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getBigdecId() == null ? 0 : this.getBigdecId().hashCode() );

         return result;
    }


}

