/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * DateOne2oneP generated by hbm2java
 */
@Entity
@Table(name="`Date_One2One_P`"
)

public class DateOne2oneP  implements java.io.Serializable {

    
    private Date dateId;
    
    private Date date1;
    
    private DateOne2oneC dateOne2oneC;

    public DateOne2oneP() {
    }


    @Id 
    @Temporal(TemporalType.DATE)

    @Column(name="`DateID`", length=10)
    public Date getDateId() {
        return this.dateId;
    }
    
    public void setDateId(Date dateId) {
        this.dateId = dateId;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`Date1`", length=10)
    public Date getDate1() {
        return this.date1;
    }
    
    public void setDate1(Date date1) {
        this.date1 = date1;
    }

    @Transient @OneToOne(fetch=FetchType.EAGER, mappedBy="dateOne2oneP")
    public DateOne2oneC getDateOne2oneC() {
        return this.dateOne2oneC;
    }
    
    public void setDateOne2oneC(DateOne2oneC dateOne2oneC) {
        this.dateOne2oneC = dateOne2oneC;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof DateOne2oneP) )
		    return false;

		 DateOne2oneP that = (DateOne2oneP) o;

		 return ( (this.getDateId()==that.getDateId()) || ( this.getDateId()!=null && that.getDateId()!=null && this.getDateId().equals(that.getDateId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getDateId() == null ? 0 : this.getDateId().hashCode() );

         return result;
    }


}

