/**This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

@TypeDefs({
                        @TypeDef(
                         name = "DateTime",
                         defaultForType = org.joda.time.LocalDateTime.class,
                         typeClass = com.wavemaker.studio.common.data.type.WMPersistentLocalDateTime.class
               )
         })

package com.dbscenarios_30mar.allo2m_o2o;

import org.hibernate.annotations.TypeDefs;
import org.hibernate.annotations.TypeDef;
