/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * TimeMany2oneP generated by hbm2java
 */
@Entity
@Table(name="`Time_Many2One_P`"
)

public class TimeMany2oneP  implements java.io.Serializable {

    
    private Date timeId;
    
    private Date timeCol1;
    
    private Set<TimeMany2oneC> timeMany2oneCs = new HashSet<TimeMany2oneC>(0);

    public TimeMany2oneP() {
    }


    @Id 
    @Temporal(TemporalType.TIME)

    @Column(name="`TimeID`", length=8)
    public Date getTimeId() {
        return this.timeId;
    }
    
    public void setTimeId(Date timeId) {
        this.timeId = timeId;
    }

    @Temporal(TemporalType.TIME)

    @Column(name="`TimeCol1`", length=8)
    public Date getTimeCol1() {
        return this.timeCol1;
    }
    
    public void setTimeCol1(Date timeCol1) {
        this.timeCol1 = timeCol1;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="timeMany2oneP")
    public Set<TimeMany2oneC> getTimeMany2oneCs() {
        return this.timeMany2oneCs;
    }
    
    public void setTimeMany2oneCs(Set<TimeMany2oneC> timeMany2oneCs) {
        this.timeMany2oneCs = timeMany2oneCs;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof TimeMany2oneP) )
		    return false;

		 TimeMany2oneP that = (TimeMany2oneP) o;

		 return ( (this.getTimeId()==that.getTimeId()) || ( this.getTimeId()!=null && that.getTimeId()!=null && this.getTimeId().equals(that.getTimeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getTimeId() == null ? 0 : this.getTimeId().hashCode() );

         return result;
    }


}

