/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * TimeStampMany2oneP generated by hbm2java
 */
@Entity
@Table(name="`TimeStamp_Many2One_P`"
)

public class TimeStampMany2oneP  implements java.io.Serializable {

    
    private Date timeStampId;
    
    private Date timeStampCol1;
    
    private Set<TimeStampMany2oneC> timeStampMany2oneCs = new HashSet<TimeStampMany2oneC>(0);

    public TimeStampMany2oneP() {
    }


    @Id 
    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`TimeStampID`", length=19)
    public Date getTimeStampId() {
        return this.timeStampId;
    }
    
    public void setTimeStampId(Date timeStampId) {
        this.timeStampId = timeStampId;
    }

    @Temporal(TemporalType.TIMESTAMP)

    @Column(name="`TimeStampCol1`", length=19)
    public Date getTimeStampCol1() {
        return this.timeStampCol1;
    }
    
    public void setTimeStampCol1(Date timeStampCol1) {
        this.timeStampCol1 = timeStampCol1;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="timeStampMany2oneP")
    public Set<TimeStampMany2oneC> getTimeStampMany2oneCs() {
        return this.timeStampMany2oneCs;
    }
    
    public void setTimeStampMany2oneCs(Set<TimeStampMany2oneC> timeStampMany2oneCs) {
        this.timeStampMany2oneCs = timeStampMany2oneCs;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof TimeStampMany2oneP) )
		    return false;

		 TimeStampMany2oneP that = (TimeStampMany2oneP) o;

		 return ( (this.getTimeStampId()==that.getTimeStampId()) || ( this.getTimeStampId()!=null && that.getTimeStampId()!=null && this.getTimeStampId().equals(that.getTimeStampId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getTimeStampId() == null ? 0 : this.getTimeStampId().hashCode() );

         return result;
    }


}

