/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.dbtest_allscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * EmployeeRelationFrom2tables generated by hbm2java
 */
@Entity
@Table(name="`Employee_RelationFrom2Tables`"
)

public class EmployeeRelationFrom2tables  implements java.io.Serializable {

    
    private Integer businessEntityId;
    
    private String nationalIdnumber;
    
    private String loginId;
    
    private String jobTitle;
    
    private String maritalStatus;
    
    private String gender;
    
    private Boolean currentFlag;
    
    private String emailId;
    
    private Short organizationLevel;
    
    private Date birthDate;
    
    private Boolean salariedFlag;
    
    private HireDateTableM2oFromEmployee hireDateTableM2oFromEmployee;
    
    private Set<CompositesKeyRelations> compositesKeyRelationses = new HashSet<CompositesKeyRelations>(0);
    
    private Set<PersonPhoneO2oM2o> personPhoneO2oM2os = new HashSet<PersonPhoneO2oM2o>(0);

    public EmployeeRelationFrom2tables() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`BusinessEntityID`", precision=10)
    public Integer getBusinessEntityId() {
        return this.businessEntityId;
    }
    
    public void setBusinessEntityId(Integer businessEntityId) {
        this.businessEntityId = businessEntityId;
    }

    

    @Column(name="`NationalIDNumber`")
    public String getNationalIdnumber() {
        return this.nationalIdnumber;
    }
    
    public void setNationalIdnumber(String nationalIdnumber) {
        this.nationalIdnumber = nationalIdnumber;
    }

    

    @Column(name="`LoginID`")
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }

    

    @Column(name="`JobTitle`")
    public String getJobTitle() {
        return this.jobTitle;
    }
    
    public void setJobTitle(String jobTitle) {
        this.jobTitle = jobTitle;
    }

    

    @Column(name="`MaritalStatus`")
    public String getMaritalStatus() {
        return this.maritalStatus;
    }
    
    public void setMaritalStatus(String maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    

    @Column(name="`Gender`")
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    

    @Column(name="`CurrentFlag`")
    public Boolean getCurrentFlag() {
        return this.currentFlag;
    }
    
    public void setCurrentFlag(Boolean currentFlag) {
        this.currentFlag = currentFlag;
    }

    

    @Column(name="`EmailId`")
    public String getEmailId() {
        return this.emailId;
    }
    
    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    

    @Column(name="`OrganizationLevel`", precision=5)
    public Short getOrganizationLevel() {
        return this.organizationLevel;
    }
    
    public void setOrganizationLevel(Short organizationLevel) {
        this.organizationLevel = organizationLevel;
    }

    @Temporal(TemporalType.DATE)

    @Column(name="`BirthDate`", length=10)
    public Date getBirthDate() {
        return this.birthDate;
    }
    
    public void setBirthDate(Date birthDate) {
        this.birthDate = birthDate;
    }

    

    @Column(name="`SalariedFlag`")
    public Boolean getSalariedFlag() {
        return this.salariedFlag;
    }
    
    public void setSalariedFlag(Boolean salariedFlag) {
        this.salariedFlag = salariedFlag;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`HireDate`")
    public HireDateTableM2oFromEmployee getHireDateTableM2oFromEmployee() {
        return this.hireDateTableM2oFromEmployee;
    }
    
    public void setHireDateTableM2oFromEmployee(HireDateTableM2oFromEmployee hireDateTableM2oFromEmployee) {
        this.hireDateTableM2oFromEmployee = hireDateTableM2oFromEmployee;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="employeeRelationFrom2tables")
    public Set<CompositesKeyRelations> getCompositesKeyRelationses() {
        return this.compositesKeyRelationses;
    }
    
    public void setCompositesKeyRelationses(Set<CompositesKeyRelations> compositesKeyRelationses) {
        this.compositesKeyRelationses = compositesKeyRelationses;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="employeeRelationFrom2tables")
    public Set<PersonPhoneO2oM2o> getPersonPhoneO2oM2os() {
        return this.personPhoneO2oM2os;
    }
    
    public void setPersonPhoneO2oM2os(Set<PersonPhoneO2oM2o> personPhoneO2oM2os) {
        this.personPhoneO2oM2os = personPhoneO2oM2os;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof EmployeeRelationFrom2tables) )
		    return false;

		 EmployeeRelationFrom2tables that = (EmployeeRelationFrom2tables) o;

		 return ( (this.getBusinessEntityId()==that.getBusinessEntityId()) || ( this.getBusinessEntityId()!=null && that.getBusinessEntityId()!=null && this.getBusinessEntityId().equals(that.getBusinessEntityId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getBusinessEntityId() == null ? 0 : this.getBusinessEntityId().hashCode() );

         return result;
    }


}

