/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.dbtest_allscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import org.hibernate.annotations.Type;
import org.joda.time.LocalDateTime;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * PhoneNumberTypeO2oPersonPhone generated by hbm2java
 */
@Entity
@Table(name="`PhoneNumberType_O2O_PersonPhone`"
)

public class PhoneNumberTypeO2oPersonPhone  implements java.io.Serializable {

    
    private Integer phoneNumberTypeId;
    
    private String name;
    
    
    @Type(type="DateTime")
    private LocalDateTime modifiedDate;
    
    private PersonPhoneO2oM2o personPhoneO2oM2o;

    public PhoneNumberTypeO2oPersonPhone() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`PhoneNumberTypeID`", precision=10)
    public Integer getPhoneNumberTypeId() {
        return this.phoneNumberTypeId;
    }
    
    public void setPhoneNumberTypeId(Integer phoneNumberTypeId) {
        this.phoneNumberTypeId = phoneNumberTypeId;
    }

    

    @Column(name="`Name`")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    

    @Column(name="`ModifiedDate`")
    public LocalDateTime getModifiedDate() {
        return this.modifiedDate;
    }
    
    public void setModifiedDate(LocalDateTime modifiedDate) {
        this.modifiedDate = modifiedDate;
    }

    @Transient @OneToOne(fetch=FetchType.EAGER, mappedBy="phoneNumberTypeO2oPersonPhone")
    public PersonPhoneO2oM2o getPersonPhoneO2oM2o() {
        return this.personPhoneO2oM2o;
    }
    
    public void setPersonPhoneO2oM2o(PersonPhoneO2oM2o personPhoneO2oM2o) {
        this.personPhoneO2oM2o = personPhoneO2oM2o;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof PhoneNumberTypeO2oPersonPhone) )
		    return false;

		 PhoneNumberTypeO2oPersonPhone that = (PhoneNumberTypeO2oPersonPhone) o;

		 return ( (this.getPhoneNumberTypeId()==that.getPhoneNumberTypeId()) || ( this.getPhoneNumberTypeId()!=null && that.getPhoneNumberTypeId()!=null && this.getPhoneNumberTypeId().equals(that.getPhoneNumberTypeId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getPhoneNumberTypeId() == null ? 0 : this.getPhoneNumberTypeId().hashCode() );

         return result;
    }


}

