/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.dbtest_allscenarios;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * StateProvinceM2oAddress generated by hbm2java
 */
@Entity
@Table(name="`StateProvince_M2O_Address`"
)

public class StateProvinceM2oAddress  implements java.io.Serializable {

    
    private Integer stateProvinceId;
    
    private String stateProvinceCode;
    
    private Boolean isOnlyStateProvinceFlag;
    
    private String name;
    
    private Integer territoryId;
    
    private CountryRegionM2oFromSp countryRegionM2oFromSp;
    
    private Set<AddressM1Sp> addressM1Sps = new HashSet<AddressM1Sp>(0);

    public StateProvinceM2oAddress() {
    }


    @Id @GeneratedValue(strategy=IDENTITY)
    

    @Column(name="`StateProvinceID`", precision=10)
    public Integer getStateProvinceId() {
        return this.stateProvinceId;
    }
    
    public void setStateProvinceId(Integer stateProvinceId) {
        this.stateProvinceId = stateProvinceId;
    }

    

    @Column(name="`StateProvinceCode`")
    public String getStateProvinceCode() {
        return this.stateProvinceCode;
    }
    
    public void setStateProvinceCode(String stateProvinceCode) {
        this.stateProvinceCode = stateProvinceCode;
    }

    

    @Column(name="`IsOnlyStateProvinceFlag`")
    public Boolean getIsOnlyStateProvinceFlag() {
        return this.isOnlyStateProvinceFlag;
    }
    
    public void setIsOnlyStateProvinceFlag(Boolean isOnlyStateProvinceFlag) {
        this.isOnlyStateProvinceFlag = isOnlyStateProvinceFlag;
    }

    

    @Column(name="`Name`")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    

    @Column(name="`TerritoryID`", precision=10)
    public Integer getTerritoryId() {
        return this.territoryId;
    }
    
    public void setTerritoryId(Integer territoryId) {
        this.territoryId = territoryId;
    }

    @ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="`CountryRegionCode`")
    public CountryRegionM2oFromSp getCountryRegionM2oFromSp() {
        return this.countryRegionM2oFromSp;
    }
    
    public void setCountryRegionM2oFromSp(CountryRegionM2oFromSp countryRegionM2oFromSp) {
        this.countryRegionM2oFromSp = countryRegionM2oFromSp;
    }

    @OneToMany(fetch=FetchType.LAZY, cascade = {CascadeType.ALL}, mappedBy="stateProvinceM2oAddress")
    public Set<AddressM1Sp> getAddressM1Sps() {
        return this.addressM1Sps;
    }
    
    public void setAddressM1Sps(Set<AddressM1Sp> addressM1Sps) {
        this.addressM1Sps = addressM1Sps;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof StateProvinceM2oAddress) )
		    return false;

		 StateProvinceM2oAddress that = (StateProvinceM2oAddress) o;

		 return ( (this.getStateProvinceId()==that.getStateProvinceId()) || ( this.getStateProvinceId()!=null && that.getStateProvinceId()!=null && this.getStateProvinceId().equals(that.getStateProvinceId()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getStateProvinceId() == null ? 0 : this.getStateProvinceId().hashCode() );

         return result;
    }


}

