/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.dbscenarios_30mar.allo2m_o2o.*;

/**
 * Service object for domain model class BigdecMany2oneP.
 * @see com.dbscenarios_30mar.allo2m_o2o.BigdecMany2oneP
 */

public interface BigdecMany2onePService {
   /**
	 * Creates a new bigdecmany2onep.
	 * 
	 * @param created
	 *            The information of the created bigdecmany2onep.
	 * @return The created bigdecmany2onep.
	 */
	public BigdecMany2oneP create(BigdecMany2oneP created);

	/**
	 * Deletes a bigdecmany2onep.
	 * 
	 * @param bigdecmany2onepId
	 *            The id of the deleted bigdecmany2onep.
	 * @return The deleted bigdecmany2onep.
	 * @throws EntityNotFoundException
	 *             if no bigdecmany2onep is found with the given id.
	 */
	public BigdecMany2oneP delete(BigDecimal bigdecmany2onepId) throws EntityNotFoundException;

	/**
	 * Finds all bigdecmany2oneps.
	 * 
	 * @return A list of bigdecmany2oneps.
	 */
	public Page<BigdecMany2oneP> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<BigdecMany2oneP> findAll(Pageable pageable);
	
	/**
	 * Finds bigdecmany2onep by id.
	 * 
	 * @param id
	 *            The id of the wanted bigdecmany2onep.
	 * @return The found bigdecmany2onep. If no bigdecmany2onep is found, this method returns
	 *         null.
	 */
	public BigdecMany2oneP findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a bigdecmany2onep.
	 * 
	 * @param updated
	 *            The information of the updated bigdecmany2onep.
	 * @return The updated bigdecmany2onep.
	 * @throws EntityNotFoundException
	 *             if no bigdecmany2onep is found with given id.
	 */
	public BigdecMany2oneP update(BigdecMany2oneP updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the bigdecmany2oneps in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the bigdecmany2onep.
	 */

	public long countAll();


    public Page<BigdecMany2oneP> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

