/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.math.BigDecimal;


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.dbscenarios_30mar.allo2m_o2o.*;

/**
 * Service object for domain model class BigdecMany2oneC.
 * @see com.dbscenarios_30mar.allo2m_o2o.BigdecMany2oneC
 */

public interface BigdecMany2oneCService {
   /**
	 * Creates a new bigdecmany2onec.
	 * 
	 * @param created
	 *            The information of the created bigdecmany2onec.
	 * @return The created bigdecmany2onec.
	 */
	public BigdecMany2oneC create(BigdecMany2oneC created);

	/**
	 * Deletes a bigdecmany2onec.
	 * 
	 * @param bigdecmany2onecId
	 *            The id of the deleted bigdecmany2onec.
	 * @return The deleted bigdecmany2onec.
	 * @throws EntityNotFoundException
	 *             if no bigdecmany2onec is found with the given id.
	 */
	public BigdecMany2oneC delete(BigDecimal bigdecmany2onecId) throws EntityNotFoundException;

	/**
	 * Finds all bigdecmany2onecs.
	 * 
	 * @return A list of bigdecmany2onecs.
	 */
	public Page<BigdecMany2oneC> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<BigdecMany2oneC> findAll(Pageable pageable);
	
	/**
	 * Finds bigdecmany2onec by id.
	 * 
	 * @param id
	 *            The id of the wanted bigdecmany2onec.
	 * @return The found bigdecmany2onec. If no bigdecmany2onec is found, this method returns
	 *         null.
	 */
	public BigdecMany2oneC findById(BigDecimal id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a bigdecmany2onec.
	 * 
	 * @param updated
	 *            The information of the updated bigdecmany2onec.
	 * @return The updated bigdecmany2onec.
	 * @throws EntityNotFoundException
	 *             if no bigdecmany2onec is found with given id.
	 */
	public BigdecMany2oneC update(BigdecMany2oneC updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the bigdecmany2onecs in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the bigdecmany2onec.
	 */

	public long countAll();


    public Page<BigdecMany2oneC> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

