/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.dbscenarios_30mar.allo2m_o2o.*;

/**
 * Service object for domain model class CharMany2oneC.
 * @see com.dbscenarios_30mar.allo2m_o2o.CharMany2oneC
 */

public interface CharMany2oneCService {
   /**
	 * Creates a new charmany2onec.
	 * 
	 * @param created
	 *            The information of the created charmany2onec.
	 * @return The created charmany2onec.
	 */
	public CharMany2oneC create(CharMany2oneC created);

	/**
	 * Deletes a charmany2onec.
	 * 
	 * @param charmany2onecId
	 *            The id of the deleted charmany2onec.
	 * @return The deleted charmany2onec.
	 * @throws EntityNotFoundException
	 *             if no charmany2onec is found with the given id.
	 */
	public CharMany2oneC delete(Character charmany2onecId) throws EntityNotFoundException;

	/**
	 * Finds all charmany2onecs.
	 * 
	 * @return A list of charmany2onecs.
	 */
	public Page<CharMany2oneC> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<CharMany2oneC> findAll(Pageable pageable);
	
	/**
	 * Finds charmany2onec by id.
	 * 
	 * @param id
	 *            The id of the wanted charmany2onec.
	 * @return The found charmany2onec. If no charmany2onec is found, this method returns
	 *         null.
	 */
	public CharMany2oneC findById(Character id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a charmany2onec.
	 * 
	 * @param updated
	 *            The information of the updated charmany2onec.
	 * @return The updated charmany2onec.
	 * @throws EntityNotFoundException
	 *             if no charmany2onec is found with given id.
	 */
	public CharMany2oneC update(CharMany2oneC updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the charmany2onecs in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the charmany2onec.
	 */

	public long countAll();


    public Page<CharMany2oneC> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

