/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.allo2m_o2o.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/




import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;

import com.dbscenarios_30mar.allo2m_o2o.*;

/**
 * Service object for domain model class StringMany2oneC.
 * @see com.dbscenarios_30mar.allo2m_o2o.StringMany2oneC
 */

public interface StringMany2oneCService {
   /**
	 * Creates a new stringmany2onec.
	 * 
	 * @param created
	 *            The information of the created stringmany2onec.
	 * @return The created stringmany2onec.
	 */
	public StringMany2oneC create(StringMany2oneC created);

	/**
	 * Deletes a stringmany2onec.
	 * 
	 * @param stringmany2onecId
	 *            The id of the deleted stringmany2onec.
	 * @return The deleted stringmany2onec.
	 * @throws EntityNotFoundException
	 *             if no stringmany2onec is found with the given id.
	 */
	public StringMany2oneC delete(String stringmany2onecId) throws EntityNotFoundException;

	/**
	 * Finds all stringmany2onecs.
	 * 
	 * @return A list of stringmany2onecs.
	 */
	public Page<StringMany2oneC> findAll(QueryFilter[] queryFilters, Pageable pageable);
	
	public Page<StringMany2oneC> findAll(Pageable pageable);
	
	/**
	 * Finds stringmany2onec by id.
	 * 
	 * @param id
	 *            The id of the wanted stringmany2onec.
	 * @return The found stringmany2onec. If no stringmany2onec is found, this method returns
	 *         null.
	 */
	public StringMany2oneC findById(String id) throws
	 EntityNotFoundException;
	/**
	 * Updates the information of a stringmany2onec.
	 * 
	 * @param updated
	 *            The information of the updated stringmany2onec.
	 * @return The updated stringmany2onec.
	 * @throws EntityNotFoundException
	 *             if no stringmany2onec is found with given id.
	 */
	public StringMany2oneC update(StringMany2oneC updated) throws EntityNotFoundException;

	/**
	 * Retrieve the total count of the stringmany2onecs in the repository.
	 * 
	 * @param None
	 *            .
	 * @return The count of the stringmany2onec.
	 */

	public long countAll();


    public Page<StringMany2oneC> findAssociatedValues(Object value, String entityName, String key,  Pageable pageable);


}

