/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.classicmodels;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Embeddable;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * MytableId generated by hbm2java
 */
@Embeddable
public class MytableId  implements java.io.Serializable {

    
    private Integer columnA;
    
    private Integer columnB;

    public MytableId() {
    }


    public Integer getColumnA() {
        return this.columnA;
    }
    
    public void setColumnA(Integer columnA) {
        this.columnA = columnA;
    }
    public Integer getColumnB() {
        return this.columnB;
    }
    
    public void setColumnB(Integer columnB) {
        this.columnB = columnB;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof MytableId) )
		    return false;

		 MytableId that = (MytableId) o;

         return ( (this.getColumnA()==that.getColumnA()) || ( this.getColumnA()!=null && that.getColumnA()!=null && this.getColumnA().equals(that.getColumnA()) ) )
 && ( (this.getColumnB()==that.getColumnB()) || ( this.getColumnB()!=null && that.getColumnB()!=null && this.getColumnB().equals(that.getColumnB()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getColumnA() == null ? 0 : this.getColumnA().hashCode() );
         result = 37 * result + ( getColumnB() == null ? 0 : this.getColumnB().hashCode() );

         return result;
    }


}

