/*Copyright (c) 2016-2017 gmail.com All Rights Reserved.
 This software is the confidential and proprietary information of gmail.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with gmail.com*/

package com.dbscenarios_30mar.classicmodels;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.Table;


import java.util.Arrays;

import javax.persistence.Transient;
import javax.persistence.CascadeType;
import javax.persistence.UniqueConstraint;



/**
 * Mytable2 generated by hbm2java
 */
@Entity
@Table(name="`mytable2`"
)
@IdClass(value=Mytable2Id.class)
public class Mytable2  implements java.io.Serializable {

    
    private Integer id;
    
    private Integer col1;
    
    private String col2;

    public Mytable2() {
    }


    @Id 
    

    @Column(name="`ID`", insertable=false, updatable=false, precision=10)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    @Id 
    

    @Column(name="`col1`", insertable=false, updatable=false, precision=10)
    public Integer getCol1() {
        return this.col1;
    }
    
    public void setCol1(Integer col1) {
        this.col1 = col1;
    }

    

    @Column(name="`col2`", length=20)
    public String getCol2() {
        return this.col2;
    }
    
    public void setCol2(String col2) {
        this.col2 = col2;
    }





    public boolean equals(Object o) {
         if (this == o) return true;
		 if ( (o == null )) return false;
		 if ( !(o instanceof Mytable2) )
		    return false;

		 Mytable2 that = (Mytable2) o;

         return ( (this.getId()==that.getId()) || ( this.getId()!=null && that.getId()!=null && this.getId().equals(that.getId()) ) )
 && ( (this.getCol1()==that.getCol1()) || ( this.getCol1()!=null && that.getCol1()!=null && this.getCol1().equals(that.getCol1()) ) )
 && ( (this.getCol2()==that.getCol2()) || ( this.getCol2()!=null && that.getCol2()!=null && this.getCol2().equals(that.getCol2()) ) );
    }

    public int hashCode() {
         int result = 17;

         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getCol1() == null ? 0 : this.getCol1().hashCode() );
         result = 37 * result + ( getCol2() == null ? 0 : this.getCol2().hashCode() );

         return result;
    }


}

